const teams = [
	{
		id: 1,
		name: 'Team Soga',
		imageUrl: require('./assets/images/soga.jpg'),
		players: [
			{
				id: 0,
				name: 'Robert',
				lastName: 'Melendez',
				number: 13,
				position: '1B',
				image: require('./assets/images/players/mike.jpg'),
			},
			{
				id: 1,
				name: 'Breidys',
				lastName: 'Melendez',
				number: 19,
				position: '3B',
				image: require('./assets/images/players/player2.jpg'),
			},
			{
				id: 2,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 3,
				name: 'Wilson',
				lastName: 'Ceballos',
				number: 12,
				position: 'LF',
				image: require('./assets/images/players/wilson.png'),
			},
			{
				id: 4,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 5,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 6,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: 'CF',
				image: require('./assets/images/players/player3.jpg'),
			},
		],
	},
	{
		id: 2,
		name: 'Team Serio',
		imageUrl: require('./assets/images/team2.jpg'),
		players: [
			{
				id: 0,
				name: 'Carlos',
				lastName: 'Reyes',
				number: 11,
				position: '1B',
				image: require('./assets/images/players/mike.jpg'),
			},
			{
				id: 1,
				name: 'Raul',
				lastName: 'Mendez',
				number: 15,
				position: '3B',
				image: require('./assets/images/players/player2.jpg'),
			},
			{
				id: 2,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 3,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 4,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 5,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 6,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
		],
	},
	{
		id: 3,
		name: 'Hato Mayor',
		// imageUrl: require('./assets/images/team2.jpg'),
		players: [
			{
				id: 0,
				name: 'Carlos',
				lastName: 'Reyes',
				number: 11,
				position: '1B',
				image: require('./assets/images/players/mike.jpg'),
			},
			{
				id: 1,
				name: 'Raul',
				lastName: 'Mendez',
				number: 15,
				position: '3B',
				image: require('./assets/images/players/player2.jpg'),
			},
			{
				id: 2,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 3,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 4,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 5,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
			{
				id: 6,
				name: 'Aneury',
				lastName: 'Ceballos',
				number: 7,
				position: '2B',
				image: require('./assets/images/players/player3.jpg'),
			},
		],
	},
];

const games = [
	{
		id: 1,
		date: new Date('2021-05-02T14:00:00').toISOString(),
		teams: [
			{ id: 1, name: 'Team Soga' },
			{ id: 2, name: 'Team Serio' },
		],
		home: {
			id: 2,
			name: 'Team Serio',
			imageUrl: require('./assets/images/team2.jpg'),
		},
		away: {
			id: 1,
			name: 'Team Soga',
			imageUrl: require('./assets/images/soga.jpg'),
		},
		location: 'Mosholu',
		won: {
			id: 1,
			name: 'Team Soga',
			imageUrl: require('./assets/images/soga.jpg'),
		},
	},
	{
		id: 2,
		date: new Date('2021-05-09T14:00:00').toISOString(),
		teams: [
			{
				id: 1,
				name: 'Team Soga',
				imageUrl: require('./assets/images/soga.jpg'),
			},
			{ id: 3, name: 'Hato Mayor' },
		],
		home: {
			id: 1,
			name: 'Team Soga',
			imageUrl: require('./assets/images/soga.jpg'),
		},
		away: { id: 3, name: 'Hato Mayor' },
		location: 'Mosholu',
		won: null,
	},
	{
		id: 3,
		date: new Date('2021-05-09T16:00:00').toISOString(),
		teams: [
			{ id: 1, name: 'Team Soga' },
			{ id: 3, name: 'Hato Mayor' },
		],
		away: {
			id: 1,
			name: 'Team Soga',
			imageUrl: require('./assets/images/soga.jpg'),
		},
		home: { id: 3, name: 'Hato Mayor' },
		location: 'Mosholu',
		won: { id: 3, name: 'Hato Mayor' },
	},
];

const positions = [
	'1B',
	'2B',
	'SS',
	'3B',
	'P',
	'C',
	'LF',
	'CF',
	'RF',
	'DH',
	'AH',
];

export { teams, games, positions };
